apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-with-quarkus-pvc
  namespace: redhat-test
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
