apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: quarkus-build
spec:
  params:
    - name: appName
      type: string
    - name: mavenOpts
      #default: "-Dquarkus.container-image.build=true -Dquarkus.container-image.push=true"
      type: string
  steps:
    - name: build-quarkus-image
      image: quay.io/openshift/pipelines-maven:v4.0
      command: ["/usr/local/bin/mvn"]
      args: ["package", "-Dnative", "$(inputs.params.mavenOpts)"]
      workingDir: $(workspaces.shared-workspace.path)
      env:
        - name: MAVEN_OPTS
          value: "$(inputs.params.mavenOpts)"

    - name: create-image
      image: quay.io/openshift/origin-cli:4.0
      command: ["oc"]
      args:
        - "new-build"
        - "--name=$(inputs.params.appName)"
        - "--binary=true"
        - "openshift/openjdk-17-rhel8"
      workingDir: $(workspaces.shared-workspace.path)

    - name: start-build
      image: quay.io/openshift/origin-cli:4.0
      command: ["oc"]
      args:
        - "start-build"
        - "--from-dir=."
        - "$(inputs.params.appName)"
      workingDir: $(workspaces.shared-workspace.path)

  workspaces:
    - name: shared-workspace
