apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: code-with-quarkus-s2i
  namespace: redhat-test
spec:
  finally:
    - name: build-quarkus
      params:
        - name: VERSION
          value: $(params.JAVA_VERSION)
        - name: PATH_CONTEXT
          value: $(params.PATH_CONTEXT)
        - name: TLSVERIFY
          value: 'false'
        - name: MAVEN_ARGS_APPEND
          value: ''
        - name: MAVEN_CLEAR_REPO
          value: 'false'
        - name: MAVEN_MIRROR_URL
          value: ''
        - name: IMAGE
          value: '$(params.IMAGE_NAME):$(params.APP_VERSION)'
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:b48f410efa0ff8ab0db6ead420a5d8d866d64af846fece5efb185230d7ecf591
        - name: SKIP_PUSH
          value: 'false'
        - name: ENV_VARS
          value: []
      taskRef:
        kind: ClusterTask
        name: s2i-java
      workspaces:
        - name: source
          workspace: shared-workspace
  params:
    - default: code-with-quarkus-s2i
      name: APP_NAME
      type: string
    - default: 1.0.0-s2i
      name: APP_VERSION
      type: string
    - default: 'https://github.com/luisfalero/code-with-quarkus'
      name: GIT_REPO
      type: string
    - default: main
      name: GIT_REVISION
      type: string
    - default: >-
        image-registry.openshift-image-registry.svc:5000/redhat-test/code-with-quarkus
      name: IMAGE_NAME
      type: string
    - default: .
      name: PATH_CONTEXT
      type: string
    - default: openjdk-17-ubi8
      name: JAVA_VERSION
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: refspec
          value: ''
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: ''
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:89fc179cd82c8ddf010af89213d3f224b99863fa21deaea5c26ab0b4c214d01b
        - name: userHome
          value: /home/git
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: unit-tests
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: unit-tests
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
  workspaces:
    - name: shared-workspace
